# Generated by Django 6.1 on 2026-08-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='role',
            field=models.CharField(choices=[('financeiro', 'Financeiro'), ('assessor', 'Assessor')], default='assessor', max_length=20, verbose_name='Função'),
        ),
    ]
