# Generated by Django 6.1 on 2026-08-17 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_assessor_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="LancamentoPJ1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data / Mês de Referência")),
                (
                    "categoria",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Categoria"
                    ),
                ),
                ("produto", models.CharField(max_length=150, verbose_name="Produto")),
                (
                    "nivel_1",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Nível 1"
                    ),
                ),
                (
                    "nivel_2",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Nível 2"
                    ),
                ),
                (
                    "nivel_3",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Nível 3"
                    ),
                ),
                (
                    "cod_cliente",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Cód. Cliente",
                    ),
                ),
                (
                    "cod_assessor_direto",
                    models.CharField(
                        max_length=50, verbose_name="Cód. Assessor Direto"
                    ),
                ),
                (
                    "receita",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Receita (R$)",
                    ),
                ),
                (
                    "receita_liquida",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Receita Líquida (R$)",
                    ),
                ),
                (
                    "repasse_escritorio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Repasse (%) Escritório",
                    ),
                ),
                (
                    "comissao_bruta_escritorio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Comissão Bruta (R$) Escritório",
                    ),
                ),
                (
                    "repasse_assessor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Repasse (%) Assessor",
                    ),
                ),
                (
                    "comissao_assessor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Comissão (R$) Assessor Direto",
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.assessor",
                        verbose_name="Assessor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LancamentoPJ2Previdencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data / Mês de Referência")),
                (
                    "classificacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Classificação",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Categoria"
                    ),
                ),
                (
                    "nivel_1",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Nível 1"
                    ),
                ),
                (
                    "nivel_2",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Nível 2"
                    ),
                ),
                (
                    "nivel_3",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Nível 3"
                    ),
                ),
                (
                    "nivel_4",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Nível 4"
                    ),
                ),
                (
                    "codigo_cliente",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Código Cliente",
                    ),
                ),
                (
                    "codigo_assessor",
                    models.CharField(max_length=50, verbose_name="Código Assessor"),
                ),
                (
                    "receita_bruta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Receita Bruta",
                    ),
                ),
                (
                    "receita_liquida",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Receita Líquida",
                    ),
                ),
                (
                    "comissao_pct_escritorio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Comissão (%) Escritório",
                    ),
                ),
                (
                    "comissao_escritorio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Comissão Escritório",
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.assessor",
                        verbose_name="Assessor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LancamentoPJ2Seguro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "seguradora",
                    models.CharField(max_length=50, verbose_name="Seguradora"),
                ),
                ("cliente", models.CharField(max_length=150, verbose_name="Cliente")),
                (
                    "comissao_bruta_escritorio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Comissão Bruta (R$) Escritório",
                    ),
                ),
                (
                    "comissao_assessor_60",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Comissão Assessor 60%",
                    ),
                ),
                (
                    "parcela",
                    models.CharField(
                        default="1/1", max_length=20, verbose_name="Parcela"
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.assessor",
                        verbose_name="Assessor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LancamentoPlus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("parceiro", models.CharField(max_length=100, verbose_name="Parceiro")),
                ("produto", models.CharField(max_length=150, verbose_name="Produto")),
                (
                    "valor_bruto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Bruto (R$)"
                    ),
                ),
                (
                    "pct_imposto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="% Imposto",
                    ),
                ),
                (
                    "valor_imposto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor Imposto (R$)",
                    ),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor Líquido (R$)",
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.assessor",
                        verbose_name="Assessor",
                    ),
                ),
            ],
        ),
    ]
