# Generated by Django 6.1 on 2026-08-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lancamentopj2seguro",
            name="parcela",
            field=models.CharField(max_length=20, verbose_name="Parcela"),
        ),
    ]
