# Generated by Django 6.1 on 2026-08-28 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_assessor_role"),
        ("finance", "0002_alter_lancamentopj2seguro_parcela"),
    ]

    operations = [
        migrations.CreateModel(
            name="LancamentoPJ2Consorcio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "administradora",
                    models.CharField(max_length=50, verbose_name="Administradora"),
                ),
                ("cliente", models.CharField(max_length=150, verbose_name="Cliente")),
                (
                    "comissao_bruta_escritorio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Comissão Bruta (R$) Escritório",
                    ),
                ),
                (
                    "comissao_assessor_60",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Comissão Assessor 60%",
                    ),
                ),
                ("parcela", models.CharField(max_length=20, verbose_name="Parcela")),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.assessor",
                        verbose_name="Assessor",
                    ),
                ),
            ],
        ),
    ]
