# Generated by Django 6.1 on 2026-08-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_lancamentopj2consorcio"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentopj2previdencia",
            name="comissao_assessor_60",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Comissão Assessor 60%",
            ),
        ),
    ]
