# Generated by Django 6.1 on 2026-09-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_fechamentocomissao"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FechamentoComissao",
        ),
    ]
