# Generated by Django 6.1 on 2026-09-02 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_assessor_role"),
        ("finance", "0006_delete_fechamentocomissao"),
    ]

    operations = [
        migrations.CreateModel(
            name="FechamentoMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competencia",
                    models.DateField(db_index=True, verbose_name="Mês de Referência"),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Pagamento"
                    ),
                ),
                (
                    "pct_imposto_pj1",
                    models.DecimalField(
                        decimal_places=2,
                        default=14.66,
                        max_digits=5,
                        verbose_name="% Imposto PJ1",
                    ),
                ),
                (
                    "pct_imposto_pj2",
                    models.DecimalField(
                        decimal_places=2,
                        default=14.66,
                        max_digits=5,
                        verbose_name="% Imposto PJ2",
                    ),
                ),
                (
                    "pct_imposto_plus",
                    models.DecimalField(
                        decimal_places=2,
                        default=6.0,
                        max_digits=5,
                        verbose_name="% Imposto PLUS",
                    ),
                ),
                (
                    "plano_saude",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Plano de Saúde (Débito)",
                    ),
                ),
                (
                    "outros_creditos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Outros Créditos",
                    ),
                ),
                (
                    "outros_debitos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Outros Débitos",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, default="", verbose_name="Observações"
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fechamentos",
                        to="accounts.assessor",
                        verbose_name="Assessor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fechamento Mensal",
                "verbose_name_plural": "Fechamentos Mensais",
                "ordering": ["-competencia", "assessor"],
                "unique_together": {("assessor", "competencia")},
            },
        ),
    ]
