# Generated by Django 6.1 on 2026-09-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_fechamentomensal"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FechamentoMensal",
        ),
    ]
