# Generated by Django 6.1 on 2026-09-02 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_assessor_role"),
        ("finance", "0008_delete_fechamentomensal"),
    ]

    operations = [
        migrations.CreateModel(
            name="FechamentoMensalAssessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competencia",
                    models.DateField(
                        db_index=True, verbose_name="Competência (Mês/Ano)"
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Pagamento"
                    ),
                ),
                (
                    "pj1_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="PJ1 Valor Bruto",
                    ),
                ),
                (
                    "pct_imposto_pj1",
                    models.DecimalField(
                        decimal_places=2,
                        default=14.66,
                        max_digits=5,
                        verbose_name="% Imposto PJ1",
                    ),
                ),
                (
                    "pj1_imposto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="PJ1 Valor Imposto",
                    ),
                ),
                (
                    "pj1_liquido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="PJ1 Valor Líquido",
                    ),
                ),
                (
                    "pj2_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="PJ2 Valor Bruto",
                    ),
                ),
                (
                    "pct_imposto_pj2",
                    models.DecimalField(
                        decimal_places=2,
                        default=14.66,
                        max_digits=5,
                        verbose_name="% Imposto PJ2",
                    ),
                ),
                (
                    "pj2_imposto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="PJ2 Valor Imposto",
                    ),
                ),
                (
                    "pj2_liquido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="PJ2 Valor Líquido",
                    ),
                ),
                (
                    "plus_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="PLUS Valor Bruto",
                    ),
                ),
                (
                    "pct_imposto_plus",
                    models.DecimalField(
                        decimal_places=2,
                        default=6.0,
                        max_digits=5,
                        verbose_name="% Imposto PLUS",
                    ),
                ),
                (
                    "plus_imposto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="PLUS Valor Imposto",
                    ),
                ),
                (
                    "plus_liquido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="PLUS Valor Líquido",
                    ),
                ),
                (
                    "plano_saude",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Plano de Saúde (Débito)",
                    ),
                ),
                (
                    "outros_creditos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Outros Créditos",
                    ),
                ),
                (
                    "outros_debitos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Outros Débitos",
                    ),
                ),
                (
                    "total_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Total Bruto",
                    ),
                ),
                (
                    "total_imposto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Total Imposto",
                    ),
                ),
                (
                    "total_liquido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Total Líquido Final",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, default="", verbose_name="Observações"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fechamentos",
                        to="accounts.assessor",
                        verbose_name="Assessor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fechamento Mensal do Assessor",
                "verbose_name_plural": "Fechamentos Mensais dos Assessores",
                "ordering": ["-competencia", "assessor"],
                "unique_together": {("assessor", "competencia")},
            },
        ),
    ]
